# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37ddb5986e61bd35e25b0d166a03cc2f25c6cd148d849f59beae22394f798fd2d8b28feba543b51a694d4fc28c71294fbb8b089f35d35671ce31fe96e30aee39

test:
  secret_key_base: fdf49e20b43e9fa9aad02dcef2d3afb723184ba4658c3e3b6546408a4c06a5d66eb77a3128b9cbed3b3aecbdd67a4418362d4a766ad77bd436ec9de21eb39607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
